In [7]:
import pandas as pd

In [8]:
data = pd.read_csv("online_shopping_uncleaned_20000_rows.csv")
data.head()

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1.0,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,NaN,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,NaN,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3.0,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,NaN,4.0,returned,chennai,15,NaN,NaN,Platinum

In [9]:
data.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='str')

In [10]:
data.isnull().sum()

Unnamed: 0                0
CustomerID                0
Gender                    0
Location                  0
Tenure_Months             0
Transaction_ID            0
Transaction_Date          0
Product_SKU               0
Product_Description       0
Product_Category          0
Quantity                  0
Avg_Price                 0
Delivery_Charges          0
Coupon_Status             0
GST                       0
Date                      0
Offline_Spend             0
Online_Spend              0
Month                     0
Coupon_Code            3356
Discount_pct             83
Payment_Status         3252
Delivery_Days          2395
Customer_Rating        4988
Return_Status          4076
Customer_City          3421
Discount_Percent       2849
Order_Priority         3356
Support_Calls          2856
Membership             6717
dtype: int64

In [11]:
data.dtypes

Unnamed: 0               int64
CustomerID             float64
Gender                     str
Location                   str
Tenure_Months          float64
Transaction_ID         float64
Transaction_Date           str
Product_SKU                str
Product_Description        str
Product_Category           str
Quantity               float64
Avg_Price              float64
Delivery_Charges       float64
Coupon_Status              str
GST                    float64
Date                       str
Offline_Spend          float64
Online_Spend           float64
Month                    int64
Coupon_Code                str
Discount_pct           float64
Payment_Status             str
Delivery_Days              str
Customer_Rating        float64
Return_Status              str
Customer_City              str
Discount_Percent           str
Order_Priority             str
Support_Calls              str
Membership                 str
dtype: object

In [12]:
data.describe()

,Unnamed: 0,CustomerID,Tenure_Months,Transaction_ID,Quantity,Avg_Price,Delivery_Charges,GST,Offline_Spend,Online_Spend,Month,Discount_pct,Customer_Rating
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,19917.000000,15012.000000
mean,9999.500000,15384.448800,26.419000,31757.398950,4.403900,56.511257,11.07499,0.134706,2998.910000,1960.758028,6.345150,22.944219,3.175793
std,5773.647028,1790.469818,13.522188,10442.150226,21.192688,63.316612,20.61016,0.044485,1116.007655,849.627815,3.993798,7.820770,1.338989
min,0.000000,12347.000000,2.000000,16679.000000,1.000000,0.390000,0.00000,0.050000,500.000000,320.250000,1.000000,10.000000,1.000000
25%,4999.750000,13819.000000,15.000000,22285.000000,1.000000,6.180000,6.00000,0.100000,2000.000000,1296.810000,3.000000,20.000000,2.000000
50%,9999.500000,15311.000000,27.000000,34498.500000,1.000000,19.190000,6.50000,0.100000,3000.000000,1918.530000,8.000000,20.000000,4.000000
75%,14999.250000,17114.000000,38.000000,36871.000000,2.000000,119.000000,6.50000,0.180000,4000.000000,2546.580000,8.000000,30.000000,4.000000
max,19999.000000,18260.000000,50.000000,48497.000000,825.000000,355.740000,521.36000,0.180000,5000.000000,4055.300000,12.000000,30.000000,5.000000

In [13]:
data.columns = data.columns.str.strip()
data.columns = data.columns.str.replace(" ", "_")
data.columns = data.columns.str.lower()

data.columns

Index(['unnamed:_0', 'customerid', 'gender', 'location', 'tenure_months',
       'transaction_id', 'transaction_date', 'product_sku',
       'product_description', 'product_category', 'quantity', 'avg_price',
       'delivery_charges', 'coupon_status', 'gst', 'date', 'offline_spend',
       'online_spend', 'month', 'coupon_code', 'discount_pct',
       'payment_status', 'delivery_days', 'customer_rating', 'return_status',
       'customer_city', 'discount_percent', 'order_priority', 'support_calls',
       'membership'],
      dtype='str')

In [25]:
data = data.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
data["payment_status"] = data["payment_status"].str.lower()
data["coupon_code"] = data["coupon_code"].str.upper()
print(data["payment_status"].head())
print(data["coupon_code"].head())

0    pending
1    unknown
2    unknown
3       paid
4    pending
Name: payment_status, dtype: str
0      UNKNOWN
1         NONE
2      NEWUSER
3       SALE20
4    NO_COUPON
Name: coupon_code, dtype: str

In [28]:
data["delivery_days"] = pd.to_numeric(data["delivery_days"], errors="coerce")
data["customer_rating"] = pd.to_numeric(data["customer_rating"], errors="coerce")
print(data["delivery_days"].head())
print(data["customer_rating"].head())
print(data[["delivery_days", "customer_rating"]].dtypes)

0    1.0
1    3.0
2    5.0
3    1.0
4    3.0
Name: delivery_days, dtype: float64
0    1.000000
1    3.175793
2    3.175793
3    3.000000
4    4.000000
Name: customer_rating, dtype: float64
delivery_days      float64
customer_rating    float64
dtype: object

In [16]:
print("Duplicates:", data.duplicated().sum())

data = data.drop_duplicates()

print("After remove:", data.shape)

Duplicates: 0
After remove: (20000, 30)

In [29]:
# check before filling
if "customer_rating" in data.columns:
    data["customer_rating"] = data["customer_rating"].fillna(data["customer_rating"].mean())

if "payment_status" in data.columns:
    data["payment_status"] = data["payment_status"].fillna("unknown")

if "delivery_days" in data.columns:
    data["delivery_days"] = data["delivery_days"].fillna(data["delivery_days"].median())

if "coupon_code" in data.columns:
    data["coupon_code"] = data["coupon_code"].fillna("no_coupon")

data.isnull().sum()

unnamed:_0                0
customerid                0
gender                    0
location                  0
tenure_months             0
transaction_id            0
transaction_date          0
product_sku               0
product_description       0
product_category          0
quantity                  0
avg_price                 0
delivery_charges          0
coupon_status             0
gst                       0
date                      0
offline_spend             0
online_spend              0
month                     0
coupon_code               0
discount_pct             83
payment_status            0
delivery_days             0
customer_rating           0
return_status          4076
customer_city          3421
discount_percent       2849
order_priority         3356
support_calls          2856
membership             6717
dtype: int64

In [31]:
import pandas as pd
import numpy as np

In [33]:
print(data.describe(include="all"))

          unnamed:_0    customerid gender location  tenure_months  \
count   20000.000000  20000.000000  20000    20000   20000.000000
unique           NaN           NaN      2        5            NaN
top              NaN           NaN      F  Chicago            NaN
freq             NaN           NaN  12195     6864            NaN
mean     9999.500000  15384.448800    NaN      NaN      26.419000
std      5773.647028   1790.469818    NaN      NaN      13.522188
min         0.000000  12347.000000    NaN      NaN       2.000000
25%      4999.750000  13819.000000    NaN      NaN      15.000000
50%      9999.500000  15311.000000    NaN      NaN      27.000000
75%     14999.250000  17114.000000    NaN      NaN      38.000000
max     19999.000000  18260.000000    NaN      NaN      50.000000

        transaction_id transaction_date     product_sku  \
count     20000.000000            20000           20000
unique             NaN              154            1012
top                NaN       2019-08-16  GGOENEBJ079499
freq               NaN              294            1744
mean      31757.398950              NaN             NaN
std       10442.150226              NaN             NaN
min       16679.000000              NaN             NaN
25%       22285.000000              NaN             NaN
50%       34498.500000              NaN             NaN
75%       36871.000000              NaN             NaN
max       48497.000000              NaN             NaN

                                      product_description product_category  \
count                                               20000            20000
unique                                                385               20
top     Nest Learning Thermostat 3rd Gen-USA - Stainle...          Apparel
freq                                                 1744             6554
mean                                                  NaN              NaN
std                                                   NaN              NaN
min                                                   NaN              NaN
25%                                                   NaN              NaN
50%                                                   NaN              NaN
75%                                                   NaN              NaN
max                                                   NaN              NaN

        ...  discount_pct  payment_status  delivery_days customer_rating  \
count   ...  19917.000000           20000   20000.000000    20000.000000
unique  ...           NaN               5            NaN             NaN
top     ...           NaN         unknown            NaN             NaN
freq    ...           NaN            6606            NaN             NaN
mean    ...     22.944219             NaN       3.367450        3.175793
std     ...      7.820770             NaN       1.732507        1.160052
min     ...     10.000000             NaN       1.000000        1.000000
25%     ...     20.000000             NaN       2.000000        3.000000
50%     ...     20.000000             NaN       3.000000        3.175793
75%     ...     30.000000             NaN       3.000000        4.000000
max     ...     30.000000             NaN       7.000000        5.000000

        return_status customer_city  discount_percent  order_priority  \
count           15924         16579             17151           16644
unique              4             5                 6               5
top              NONE        Mumbai               25%            High
freq             4074          3403              2917            3396
mean              NaN           NaN               NaN             NaN
std               NaN           NaN               NaN             NaN
min               NaN           NaN               NaN             NaN
25%               NaN           NaN               NaN             NaN
50%               NaN           NaN               NaN             NaN
75%               NaN           NaN               NaN             NaN
max               NaN           NaN               NaN             NaN

        support_calls membership
count           17144      13283
unique              6          4
top                 1       Gold
freq             2897       3342
mean              NaN        NaN
std               NaN        NaN
min               NaN        NaN
25%               NaN        NaN
50%               NaN        NaN
75%               NaN        NaN
max               NaN        NaN

[11 rows x 30 columns]

In [35]:
print(data.nunique())

unnamed:_0             20000
customerid               889
gender                     2
location                   5
tenure_months             49
transaction_id         10153
transaction_date         154
product_sku             1012
product_description      385
product_category          20
quantity                 111
avg_price                457
delivery_charges         185
coupon_status              3
gst                        4
date                     154
offline_spend             11
online_spend             154
month                      5
coupon_code                6
discount_pct               3
payment_status             5
delivery_days              5
customer_rating            6
return_status              4
customer_city              5
discount_percent           6
order_priority             5
support_calls              6
membership                 4
dtype: int64

In [37]:
data = data.replace("unknown", np.nan)
data = data.replace("NONE", np.nan)
data = data.replace("none", np.nan)

print(data.isnull().sum())

unnamed:_0                0
customerid                0
gender                    0
location                  0
tenure_months             0
transaction_id            0
transaction_date          0
product_sku               0
product_description       0
product_category          0
quantity                  0
avg_price                 0
delivery_charges          0
coupon_status             0
gst                       0
date                      0
offline_spend             0
online_spend              0
month                     0
coupon_code            3347
discount_pct             83
payment_status         6606
delivery_days             0
customer_rating           0
return_status          8150
customer_city          3421
discount_percent       5668
order_priority         6700
support_calls          5702
membership             6717
dtype: int64

In [39]:
data["customer_city"] = data["customer_city"].str.title()
print(data["customer_city"].head())

0      Unknown
1          NaN
2       Mumbai
3     Chennai
4     Chennai
Name: customer_city, dtype: str

In [41]:
data["coupon_code"] = data["coupon_code"].fillna("No Coupon")
data["coupon_code"] = data["coupon_code"].str.strip().str.upper()
print(data["coupon_code"].head())

0      UNKNOWN
1    NO COUPON
2      NEWUSER
3       SALE20
4    NO_COUPON
Name: coupon_code, dtype: str

In [43]:
data["discount_percent"] = pd.to_numeric(
    data["discount_percent"].astype(str).str.replace("%", "", regex=False).str.strip(),
    errors="coerce"
)
print(data["discount_percent"].head())
print(data["discount_percent"].dtype)

0    25.0
1    25.0
2     NaN
3     NaN
4    15.0
Name: discount_percent, dtype: float64
float64

In [45]:
data["support_calls"] = pd.to_numeric(
    data["support_calls"].astype(str).str.replace("calls", "", regex=False).str.strip(),
    errors="coerce"
)
print(data["support_calls"].head())
print(data["support_calls"].dtype)

0    3.0
1    4.0
2    0.0
3    3.0
4    NaN
Name: support_calls, dtype: float64
float64

In [58]:
data["discount_percent"] = data["discount_percent"].fillna(data["discount_percent"].median())
data["support_calls"] = data["support_calls"].fillna(data["support_calls"].median())
data["return_status"] = data["return_status"].fillna("Unknown")
data["customer_city"] = data["customer_city"].fillna("Unknown")
data["order_priority"] = data["order_priority"].fillna("Unknown")
data["membership"] = data["membership"].fillna("Unknown")

print(data.isnull().sum())

unnamed:_0                0
customerid                0
gender                    0
location                  0
tenure_months             0
transaction_id            0
transaction_date          0
product_sku               0
product_description       0
product_category          0
quantity                  0
avg_price                 0
delivery_charges          0
coupon_status             0
gst                       0
date                      0
offline_spend             0
online_spend              0
month                     0
coupon_code               0
discount_pct             83
payment_status         6606
delivery_days             0
customer_rating           0
return_status             0
customer_city             0
discount_percent          0
order_priority            0
support_calls             0
membership                0
dtype: int64

In [49]:
print(data.duplicated().sum())

0

In [51]:
data = data.drop_duplicates()
print(data.shape)

(20000, 30)

In [53]:
print("Total orders:", len(data))

Total orders: 20000

In [55]:
print(data["payment_status"].value_counts(dropna=False))

payment_status
NaN        6606
failed     3430
 paid      3406
pending    3337
paid       3221
Name: count, dtype: int64

In [57]:
print(data["payment_status"].value_counts().idxmax())

failed

In [60]:
print(data["customer_rating"].mean())

3.175792699173994

In [62]:
print(data[data["customer_rating"] < 3][["customerid", "customer_rating"]])

       customerid  customer_rating
0         17850.0              1.0
5         17850.0              2.0
16        17850.0              2.0
24        13047.0              2.0
29        14688.0              1.0
...           ...              ...
19981     14401.0              2.0
19985     15194.0              2.0
19990     14309.0              1.0
19997     17790.0              2.0
19999     17404.0              2.0

[4954 rows x 2 columns]

In [64]:
print(data["membership"].value_counts(dropna=False))

membership
Unknown     6717
Gold        3342
Silver      3338
Platinum    3327
 gold       3276
Name: count, dtype: int64

In [66]:
print(data[data["delivery_days"] > 7])

Empty DataFrame
Columns: [unnamed:_0, customerid, gender, location, tenure_months, transaction_id, transaction_date, product_sku, product_description, product_category, quantity, avg_price, delivery_charges, coupon_status, gst, date, offline_spend, online_spend, month, coupon_code, discount_pct, payment_status, delivery_days, customer_rating, return_status, customer_city, discount_percent, order_priority, support_calls, membership]
Index: []

[0 rows x 30 columns]

In [67]:
print(data["delivery_days"].mean())

3.36745

In [69]:
print((data["delivery_days"] > 7).sum())

0

In [71]:
print(data.groupby("order_priority")["delivery_days"].mean())

order_priority
 high      3.381643
High       3.358657
Low        3.343628
Medium     3.365367
Unknown    3.377761
Name: delivery_days, dtype: float64

In [73]:
print(data.groupby("order_priority")["delivery_days"].mean().idxmin())

Low

In [75]:
print(data["discount_percent"].mean())

14.9995

In [77]:
print(data[data["discount_percent"] == data["discount_percent"].max()])

       unnamed:_0  customerid gender    location  tenure_months  \
0               0     17850.0      M     Chicago           12.0
1               1     17850.0      M     Chicago           12.0
11             11     17850.0      M     Chicago           12.0
18             18     17850.0      M     Chicago           12.0
22             22     17850.0      M     Chicago           12.0
...           ...         ...    ...         ...            ...
19964       19964     13846.0      F  New Jersey            4.0
19971       19971     13846.0      F  New Jersey            4.0
19977       19977     14401.0      F  California           20.0
19988       19988     18116.0      F     Chicago           38.0
19995       19995     13854.0      F     Chicago           44.0

       transaction_id transaction_date     product_sku  \
0             16679.0       2019-01-01  GGOENEBJ079499
1             16680.0       2019-01-01  GGOENEBJ079499
11            16719.0       2019-01-01  GGOENEBJ079499
18            16723.0       2019-01-01  GGOENEBQ078999
22            16731.0       2019-01-01  GGOENEBQ078999
...               ...              ...             ...
19964         29407.0       2019-06-02  GGOEGOAA017199
19971         29407.0       2019-06-02  GGOEGOBG023599
19977         29465.0       2019-06-02  GGOEAFKQ020599
19988         30616.0       2019-06-17  GGOEGOAQ012899
19995         31174.0       2019-06-25  GGOEGFKA022299

                                     product_description product_category  \
0      Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
1      Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
11     Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
18                Nest Cam Outdoor Security Camera - USA         Nest-USA
22                Nest Cam Outdoor Security Camera - USA         Nest-USA
...                                                  ...              ...
19964                   Rubber Grip Ballpoint Pen 4 Pack           Office
19971                                 Colored Pencil Set           Office
19977              Android Sticker Sheet Ultra Removable           Office
19988                            Ballpoint LED Light Pen           Office
19995                               Keyboard DOT Sticker           Office

       ...  discount_pct  payment_status  delivery_days customer_rating  \
0      ...          10.0         pending            1.0        1.000000
1      ...          10.0             NaN            3.0        3.175793
11     ...          10.0         pending            2.0        4.000000
18     ...          10.0             NaN            3.0        4.000000
22     ...          10.0          failed            2.0        3.000000
...    ...           ...             ...            ...             ...
19964  ...          30.0          failed            3.0        1.000000
19971  ...          30.0             NaN            2.0        2.000000
19977  ...          30.0          failed            3.0        3.000000
19988  ...          30.0             NaN            1.0        3.175793
19995  ...          30.0             NaN            1.0        3.175793

       return_status customer_city  discount_percent  order_priority  \
0          returned        Unknown              25.0            High
1            Unknown       Unknown              25.0          Medium
11           Unknown         Delhi              25.0            High
18           Unknown         Delhi              25.0            High
22           Unknown       Unknown              25.0         Unknown
...              ...           ...               ...             ...
19964        Unknown       Unknown              25.0            High
19971   Not Returned       Unknown              25.0          Medium
19977        Unknown        Mumbai              25.0           high
19988        Unknown       Unknown              25.0         Unknown
19995      returned        Unknown              25.0            High

       support_calls membership
0                3.0       Gold
1                4.0    Unknown
11               0.0       Gold
18               2.0      gold
22               4.0    Unknown
...              ...        ...
19964            0.0   Platinum
19971            2.0     Silver
19977            2.0    Unknown
19988            3.0     Silver
19995            4.0    Unknown

[2917 rows x 30 columns]

In [79]:
print((data["coupon_code"].astype(str).str.lower() != "no coupon").sum())

16653

In [81]:
print(data.loc[data["coupon_code"].astype(str).str.lower() != "no coupon", "coupon_code"].value_counts().idxmax())

UNKNOWN

In [83]:
data["price_after_discount"] = data["avg_price"] * (1 - data["discount_percent"] / 100)
print(data[["avg_price", "discount_percent", "price_after_discount"]].head())

   avg_price  discount_percent  price_after_discount
0     153.71              25.0              115.2825
1     153.71              25.0              115.2825
2     122.77              15.0              104.3545
3      81.50              15.0               69.2750
4     153.71              15.0              130.6535

In [85]:
print(data["support_calls"].mean())

1.99055

In [87]:
print(data[data["support_calls"] > 2])

       unnamed:_0  customerid gender    location  tenure_months  \
0               0     17850.0      M     Chicago           12.0
1               1     17850.0      M     Chicago           12.0
3               3     17850.0      M     Chicago           12.0
19             19     17850.0      M     Chicago           12.0
22             22     17850.0      M     Chicago           12.0
...           ...         ...    ...         ...            ...
19993       19993     16013.0      M    New York           31.0
19994       19994     16013.0      M    New York           31.0
19995       19995     13854.0      F     Chicago           44.0
19998       19998     12370.0      F    New York           21.0
19999       19999     17404.0      F  New Jersey           11.0

       transaction_id transaction_date     product_sku  \
0             16679.0       2019-01-01  GGOENEBJ079499
1             16680.0       2019-01-01  GGOENEBJ079499
3             16699.0       2019-01-01  GGOENEBQ079099
19            16724.0       2019-01-01  GGOENEBB078899
22            16731.0       2019-01-01  GGOENEBQ078999
...               ...              ...             ...
19993         31175.0       2019-06-25  GGOEAFKQ020599
19994         31175.0       2019-06-25  GGOEGFKA022299
19995         31174.0       2019-06-25  GGOEGFKA022299
19998         31175.0       2019-06-25  GGOEGFKQ020399
19999         31214.0       2019-06-25  GGOEGFKQ020399

                                     product_description product_category  \
0      Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
1      Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
3        Nest Protect Smoke + CO White Battery Alarm-USA         Nest-USA
19                 Nest Cam Indoor Security Camera - USA         Nest-USA
22                Nest Cam Outdoor Security Camera - USA         Nest-USA
...                                                  ...              ...
19993              Android Sticker Sheet Ultra Removable           Office
19994                               Keyboard DOT Sticker           Office
19995                               Keyboard DOT Sticker           Office
19998              Google Laptop and Cell Phone Stickers           Office
19999              Google Laptop and Cell Phone Stickers           Office

       ...  payment_status  delivery_days  customer_rating return_status  \
0      ...         pending            1.0         1.000000     returned
1      ...             NaN            3.0         3.175793       Unknown
3      ...            paid            1.0         3.000000     returned
19     ...          failed            3.0         5.000000       Unknown
22     ...          failed            2.0         3.000000       Unknown
...    ...             ...            ...              ...           ...
19993  ...         pending            3.0         3.175793       Unknown
19994  ...            paid            7.0         3.175793  Not Returned
19995  ...             NaN            1.0         3.175793     returned
19998  ...         pending            7.0         3.175793     returned
19999  ...             NaN            1.0         2.000000  Not Returned

       customer_city discount_percent  order_priority  support_calls  \
0            Unknown             25.0            High            3.0
1            Unknown             25.0          Medium            4.0
3           Chennai              15.0             Low            3.0
19           Unknown              5.0            High            3.0
22           Unknown             25.0         Unknown            4.0
...              ...              ...             ...            ...
19993        Unknown              5.0             Low            3.0
19994       Chennai               5.0             Low            3.0
19995        Unknown             25.0            High            4.0
19998        Unknown             15.0         Unknown            4.0
19999        Chennai             15.0             Low            4.0

       membership price_after_discount
0            Gold             115.2825
1         Unknown             115.2825
3            Gold              69.2750
19           Gold             116.6315
22        Unknown              92.0775
...           ...                  ...
19993     Unknown               2.8405
19994       gold                1.4250
19995     Unknown               1.1250
19998        Gold               2.5415
19999       gold                2.5415

[5675 rows x 31 columns]

In [89]:
print(pd.crosstab(data["support_calls"], data["return_status"]))

return_status   returned   Not Returned  Returned  Unknown
support_calls
0.0                   566           565       593     1154
1.0                   571           579       558     1189
2.0                  1651          1739      1659     3501
3.0                   583           564       567     1172
4.0                   619           529       507     1134

In [91]:
print(data[(data["support_calls"] > 2) & (data["return_status"].astype(str).str.lower() == "returned")])

       unnamed:_0  customerid gender    location  tenure_months  \
24             24     13047.0      M  California           43.0
43             43     17511.0      F     Chicago           25.0
180           180     17920.0      F  California           18.0
212           212     14606.0      F     Chicago           33.0
239           239     15694.0      F    New York           41.0
...           ...         ...    ...         ...            ...
19943       19943     16817.0      M  California           20.0
19965       19965     13846.0      F  New Jersey            4.0
19974       19974     13846.0      F  New Jersey            4.0
19975       19975     13846.0      F  New Jersey            4.0
19985       19985     15194.0      M     Chicago           33.0

       transaction_id transaction_date     product_sku  \
24            16684.0       2019-01-01  GGOENEBQ079199
43            16826.0       2019-01-03  GGOENEBJ079499
180           17068.0       2019-01-04  GGOENEBQ079099
212           17970.0       2019-01-16  GGOENEBB078899
239           18013.0       2019-01-16  GGOENEBQ079199
...               ...              ...             ...
19943         29478.0       2019-06-02  GGOEYOLR018699
19965         29407.0       2019-06-02  GGOEGOAB021699
19974         29410.0       2019-06-02  GGOEAFKQ020599
19975         29411.0       2019-06-02  GGOEGOGA016299
19985         30614.0       2019-06-17  GGOEGGOA017399

                                     product_description product_category  \
24         Nest Protect Smoke + CO White Wired Alarm-USA         Nest-USA
43     Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
180      Nest Protect Smoke + CO White Battery Alarm-USA         Nest-USA
212                Nest Cam Indoor Security Camera - USA         Nest-USA
239        Nest Protect Smoke + CO White Wired Alarm-USA         Nest-USA
...                                                  ...              ...
19943                 YouTube Leatherette Notebook Combo           Office
19965                         Google Ballpoint Pen Black           Office
19974              Android Sticker Sheet Ultra Removable           Office
19975                        Grip Highlighter Pen 3 Pack           Office
19985                                           Maze Pen           Office

       ...  payment_status  delivery_days  customer_rating return_status  \
24     ...          failed            7.0         2.000000      Returned
43     ...          failed            2.0         3.175793      Returned
180    ...         pending            2.0         4.000000      Returned
212    ...           paid             3.0         1.000000      Returned
239    ...           paid             2.0         1.000000      Returned
...    ...             ...            ...              ...           ...
19943  ...            paid            2.0         4.000000      Returned
19965  ...          failed            2.0         4.000000      Returned
19974  ...             NaN            3.0         4.000000      Returned
19975  ...          failed            3.0         3.175793      Returned
19985  ...             NaN            7.0         2.000000      Returned

       customer_city discount_percent  order_priority  support_calls  \
24             Delhi              5.0             Low            3.0
43           Unknown             10.0         Unknown            3.0
180            Delhi             10.0         Unknown            3.0
212           Mumbai             10.0           high             3.0
239          Unknown             10.0           high             3.0
...              ...              ...             ...            ...
19943          Delhi             10.0          Medium            3.0
19965        Chennai             15.0         Unknown            4.0
19974          Delhi             10.0          Medium            3.0
19975         Mumbai             15.0          Medium            3.0
19985         Mumbai             10.0           high             3.0

       membership price_after_discount
24       Platinum              77.4250
43        Unknown             138.3390
180       Unknown              73.3500
212          Gold             110.4930
239         gold               73.3500
...           ...                  ...
19943       gold                6.2910
19965    Platinum               1.6915
19974     Unknown               2.6910
19975        Gold               2.9665
19985      Silver               0.7110

[1074 rows x 31 columns]

In [93]:
data.to_csv("clean_online_shopping.csv", index=False)

In [97]:
analysis_results = {
    "Total Orders": len(data),
    "Returned Orders": (data["return_status"].astype(str).str.lower() == "returned").sum(),
    "Return Percentage": ((data["return_status"].astype(str).str.lower() == "returned").sum() / len(data)) * 100,
    "Average Customer Rating": data["customer_rating"].mean(),
    "Average Delivery Days": data["delivery_days"].mean(),
    "Average Discount Percent": data["discount_percent"].mean(),
    "Average Support Calls": data["support_calls"].mean()
}

analysis_df = pd.DataFrame(list(analysis_results.items()), columns=["Metric", "Value"])
analysis_df.to_csv("analysis_results.csv", index=False)

print("analysis_results.csv saved successfully")

analysis_results.csv saved successfully